### ISSUE TITLE
[ICO] Please update the ICO file for Windows

### ISSUE THREAD

**Issue by Bastien-Satochip** [Toporin/Satochip-Utils#5]
The current ICO file looks like this:
![image](https://github.com/Toporin/Satochip-Utils/assets/87421384/cd543349-5fd7-4501-93b7-b4b78d16804e)

Please update it using one of the following files...
![Satochip-Utils-48](https://github.com/Toporin/Satochip-Utils/assets/87421384/467307e7-09ac-4abd-8066-00f24c66d8db)
![Satochip-Utils-256](https://github.com/Toporin/Satochip-Utils/assets/87421384/3a0f3b74-0e72-4df3-8909-b61556ec744e)
![Satochip-Utils-512](https://github.com/Toporin/Satochip-Utils/assets/87421384/fe41e8f5-b355-41b9-a5d6-f7a9279f8394)

To make it look like this:
![image](https://github.com/Toporin/Satochip-Utils/assets/87421384/1e4c929a-e20c-4552-af96-ebc6e890adbe)

**Comment by Toporin** [comment]
I need an .ico file (size should  be around ~20kb)

**Comment by Bastien-Satochip** [comment]
How about this one... It's 35ko - can't make it lighter. 
If it's a problem, I will reduce the quality.

[Satochip-Utils.zip](https://github.com/user-attachments/files/17933787/Satochip-Utils.zip)
